version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - ./sls.sh deploy -v -s $STAGE
  post_build:
    commands:
      - echo Build completed on `date`